HubSpot/cms-theme-boilerplate

src/templates/blog-index.html
This PR updates the blog template so that the large "featured blog post" is only displayed on the first page of the listing. Pages 2 and beyond just show a grid.
=> Only show big blog post on page 1

src/modules/Pricing card.module/fields.json, src/modules/Pricing card.module/module.html
This PR includes the following improvements to the Pricing card module:
- Remove div/span wrapper from icons so that the display in the editor
matches the published page
- Fix HTML
- Remove unused field
- Remove field ids which are no longer needed for simple modules
Before:
After:
=> Improve Pricing card module

src/css/_blog.css, src/css/main.css, src/templates/blog-index.html
Currently, when a featured image isn't set there is a big empty space left. In and effort to encourage featured image use, this PR sets a fallback image that will display when no featured image is set.
=> Add fallback images for blog featured images

src/templates/layouts/base.html
Switches the base template to use the `page_met`a object for meta fields since those contain information about overrides coming from the CMS.
=> Switch to page meta object

src/css/_blog.css, src/templates/blog-index.html
Fixes #39 
Restructures blog pagination markup and fixes alignment on desktop/mobile. Also hides pagination if there is only one page of blog posts.
Before: 
After:
=> Fix blog pagination alignment

src/css/_header.css, src/modules/Menu section.module/module.css, src/templates/partials/header.html
Merged two of the discussed design styles, since the boilerplate home page menu was overlapping again. Previously, I bumped up the mobile breakpoint to "fix" this issue but this is my attempt at a more resilient solution. 
At 1150px, the tablet breakpoint takes place, moving the logo into the top column while the menu takes the space below it. The menu specifically has "nowrap" on it, so that an obscenely long menu won't cause an unsightly menu wrap.
=> added some opinionated tablet styles

src/templates/about.html, src/templates/contact.html, src/templates/homepage.html, src/templates/landing-page.html, src/templates/pricing.html
Resolves #63 
* Removes `label` where module name is the same
* Opts for inline params over module_attribute blocks where they're nicer to read
* Cleans up some unneeded module params that might lead to confusion
=> Clean up module attributes

src/modules/Menu section.module/meta.json
menu section is the only boilerplate module with a module_id. Removing it from boilerplate to make it more clear that developers should have their own unique instances of this menu module and avoid collisions.
=> Remove module_id from menu section

src/css/theme-overrides.css
This removes opacity style from links as the opacity parameter is set to be hidden on the field.
=> Remove opacity style when hidden

src/css/_forms.css, src/css/theme-overrides.css, src/templates/system/membership_login.html, src/templates/system/membership_register.html, src/templates/system/membership_reset_password.html, src/templates/system/membership_reset_password_request.html
Adds 4 template types:
- Membership Registration (`membership_register_page`)
- Membership Login Page (`membership_login_page`)
- Reset Password Request Page (`membership_reset_request_page`)
- Reset Password Page (`membership_reset_page`)
Membership registration access allows users to publish permissions that can control which contacts can access HubSpot-hosted pages, blogs, and knowledge base articles.
**Note:** Membership templates are only available to Marketing Hub Professions, Marketing Hub Enterprise, and CMS accounts. To learn more please see the [Membership Registration documentation](https://knowledge.hubspot.com/cms-pages-editor/control-audience-access-to-pages).
Fixes #74
=> Add membership templates

src/css/_forms.css
Updating the styles for buttons so that `white-space: normal;` is added. This prevents the buttons from extending across the page instead of wrapping the text at the container width, which is the expected behavior.
=> adding `white-space: normal;` to CSS for buttons

src/css/theme-overrides.css, src/modules/menu-section.module/module.css
1. Updating the border on the menu so it isn't jagged/disconnected anymore
2. Updating the triangle on the menu so that it is hooked up to theme settings and is in line with the rest of menu border
Updated styles screenshot:
Hover state:
=> Updates to the menu border and triangle CSS

src/css/_forms.css, src/css/theme-overrides.css, src/modules/customizable-button.module/module.html, src/templates/system/404.html
Replacing instances of `hs-button` with `button` on non HubSpot generated buttons (e.g. the form submit button). 
Fixes #61 and will replace (https://github.com/HubSpot/cms-theme-boilerplate/pull/62). This needed to be fixed up first so that I could start style guiding templates (as `hs-button` was used on the 404 error template).
=> Updating button class name

src/css/components/_footer.css, src/css/elements/_forms.css, src/css/objects/_containers-dnd.css, src/css/theme-overrides.css, src/css/tools/_macros.css, src/fields.json
Updating fields.json and theme-overrides.css to meet style guide requirements. Some pieces in addition to meeting style guide: 
- Removing `opacity` on text color settings (e.g. footer text color) so that text is always clearly visible.
- Removing `opacity` on border color settings - we'll want to add additional border options in the near future (e.g. type and width). 
- Adding variables to the top of `fields.json` which helps make things easier to read below and makes it easier for a developer to replace a value used several times in the theme-overrides.css
Fixes #130 
Fixes #131 
CC: @TheWebTech @ajlaporte no breaking links but we are moving towards variables at the top of `theme-overrides.css` to make CSS below it easier to read and easier to update.
=> Updating fields.json and theme-overrides.css to meet style guide requirements

src/css/main.css
Removing `_home.css` reference in `main.css` as that template was removed. 
CC: @ckconant @TanyaScales 
Fixes #134
=> Removing home.css reference in main.css

src/templates/partials/header-no-navigation.html
- Adding `content-wrapper` class to header no nav partial (was previously incorrect)
- Adding screenshots to `theme.json` and templates 
Fixes #79 
Fixes #128 
CC: @TanyaScales @ckconant
=> Adding template and theme screenshots

src/css/theme-overrides.css, src/fields.json
Fixes #146 
The goal was to update the different font size references in the `fields.json` file of the theme. They were previously using an outdated approach and the outdated approach was being incorrectly referenced in `theme-overrides.css` which was causing an issue in the CSS and breaking CSS combining. The fix updates `fields.json` font size fields to match [our documentation](https://designers.hubspot.com/docs/building-blocks/module-theme-fields#font) and fixes references to the font fields from `theme-overrides.css`. 
We'll be making a patch release once we're able to ensure CSS combining is working after this fix.
=> Fixing theme JSON for font size

src/modules/menu-section.module/module.html
Add link target to menu links (previously wasn't set). 
Example page (About has target set: http://jrosa-102019231.hs-sitesqa.com/?hs_preview=WeodDwqu-4182245376). 
Fixes #121
=> Add link target to the menu links

src/modules/menu-section.module/fields.json
Removing the `locked` parameter on the menu field in the menu module. For context the `locked` parameter can be found under properties used by all fields here (https://designers.hubspot.com/docs/building-blocks/module-theme-fields#properties-used-by-all-fields). This was previously set to true and we are removing it so that it is now set back to the default of false as we want the menu field to be editable in content editors.
=> Removing locked option for the menu field on the menu module

src/css/components/_header.css
Removes line-height that was set on the search bar input which fixes the height.
**Example link:** (http://jrosa-102019231.hs-sitesqa.com/test)
Fixes #151
=> Removing line height on search results input

package.json
Update boilerplate version number to v1.2.3 to support patch release of template/theme screenshots.
=> Updating the version number to v1.2.3

src/modules/menu-section.module/module.js
In the menu module JavaScript, I replaced `this` with `el` within the event listeners to improve upon the readability of the code. 
Example page: https://preview.hs-sitesqa.com/_hcms/preview/template/multi?domain=undefined&portalId=102019231&tc_deviceCategory=undefined&template_file_path=CMSBoilerplate/templates/home.html&updated=1589811518449
GitHub reference: https://github.com/HubSpot/cms-theme-boilerplate/pull/169#discussion_r438434699
**Checklist**
=> Replacing this with el in menu JS

src/css/elements/_typography.css
Previously we had `word-break` set on the headings in the `typography.css`. Per feedback on our default themes we are moving `word-break: break-word` to the `body` element and have added some specific fallbacks for languages where this isn't the expected behavior. 
Fixes #182 
**Checklist**
=> Adding word break for all content with the exception of certain langs

src/css/templates/_blog.css
Currently the blog post template was not responsive as the related blog posts section at the bottom wasn't breaking down from three across to one across on mobile. I added flex-wrap to the parent container so that the child items could properly wrap on mobile. 
Fixes #132 
**Checklist**
=> Fix responsiveness of blog related posts

src/modules/menu-section.module/module.css
Previously the menu drop downs were going behind the form in the blog listing template banner. I bumped up the z-index of the drop down menus to 2 so this was no longer an issue. Please note if you use modules with a z-index higher than 2 that you may need to bump up the menu drop down z-index to be a bit higher if it is supposed to overlap the new module. 
Fixes #157 
**Checklist**
=> Fixing menu hover overlap issue

src/css/templates/_system.css
Widening out the max-width on system templates to account for larger heading sizes (previously large heading sizes weren't fitting in the specified container). 
Fixes #141 
**Checklist**
=> Adjusting system template max-width

src/templates/contact.html, src/templates/home.html, src/templates/layouts/base.html
Making a couple of small tweaks to improve the out of the box HubSpot website grader score for the HubSpot CMS Boilerplate. Currently, after adding meta descriptions for each page on (https://boilerplate.hubspotcms.com/), the website grader score is 92. 
- There was a note to be more specific with the home page button text of "Click Here" so I swapped that with "Learn More". 
- There was a note in the optimize tab of the contact page that said images didn't have alt text so I added some alt text for this.
- We were still including the fallback Google font which wasn't needed after updating boilerplate to use themes. This likely won't make a large impact but I'm removing it so that there is one less page request. 
This should likely get us to a ~97 for …
=> Improve website grader score

src/modules/pricing-card.module/fields.json, src/modules/pricing-card.module/module.html
Previously there was not a link option for the pricing card module. This PR adds a link field to the button at the bottom of the pricing card. 
Fixes #173 
**Checklist**
=> Adding link field to price card button module

src/templates/blog-index.html
This change resolves a duplicate `h1` on the blog tag listing page. 
Fixes #180 
**Checklist**
=> Fixing duplicate h1 issue on blog listing tag pages

src/css/templates/_blog.css, src/templates/blog-index.html, src/templates/blog-post.html
Adding in conditionals to ensure that the blog post and listing templates both tie into the different blog settings properly. 
Fixes #172 
**Checklist**
CC: @ajlaporte @TheWebTech I don't think there is documentation to change but just wanted to keep you in the loop on this change.
=> Blog settings

src/fields.json
The button hover/active was not working properly. Based on how we had it set up the opacity of the rgba that we had for the background color was going to 0. After looking into this further, it looks like `themes.buttons.background_color.opacity` wasn't working at all. When checking out the `fields.json` this then made sense as the background color field on the button was pulling from one of the primary colors (which didn't have an opacity set/it was hidden). So I only inherited the color and not the opacity from the primary color. 
Fixes #178 
**Checklist**
=> Fixing inherited pathfor button background color

src/css/components/_header.css, src/modules/social-follow.module/module.html, src/templates/partials/header.html
Removing duplicate ids where possible on the page. This was resolved in the for loop for the social follow module using `unique_in_loop=True` (more information here: https://developers.hubspot.com/docs/cms/hubl/for-loops#using-hubl-tags-in-loops) and was resolved for the header by removing the tablet logo and just using the main logo all the way through. 
Related to https://github.com/HubSpot/cms-theme-boilerplate/issues/181
**Checklist**
=> Remove duplicate ids

src/modules/card-section.module/module.css
Fixes image dimension problem that exists on the boilerplate contact page (https://boilerplate.hubspotcms.com/contact). Image is supposed to be a perfect square (natural dimensions of 300 x 300) but it is getting crammed based on the CSS that was being used. I simplified the CSS a bit so that this no longer happens. 
Fixes #200 
**Checklist**
=> Fixing card image dimensions

src/css/components/_header.css, src/modules/card-section.module/module.css
Fixes a bug introduced in (https://github.com/HubSpot/cms-theme-boilerplate/pull/187). It looks like the different mobile menu titles (using pseudo elements) weren't getting their default width because of the word-break that was set globally. Setting `word-break: normal;` for these elements should resolve that issue. 
**Checklist**
=> Fix mobile headings

src/css/elements/_tables.css
While we are accounting for text-wrapping here (https://github.com/HubSpot/cms-theme-boilerplate/pull/187) we wanted to add a specific style to tables so that it was clear how to add text wrapping for words within tables. 
**Checklist**
=> Adding overflow-wrap for tables

src/modules/menu-section.module/module.html
Adding the class name of `hs-skip-lang-url-rewrite` to menu items in the custom menu module [per the instructions in the last bullet point here](https://developers.hubspot.com/docs/cms/features/multi-language-content#what-hubspot-does-automatically) to remove language translation query at the end of URLs in the menu module. 
Example page: http://jrosa-102019231.hs-sitesqa.com/-temporary-slug-89d8f767-0d8e-461a-abcc-f099f31bb597?hs_preview=JRNqHsFh-4278306148
**Checklist**
CC: @TheWebTech 
CC: @LisleBuckley this is likely a change you'll want to add to your boilerplate
=> Adding lang specific classes to menu items

src/templates/blog-index.html
- Added conditionals so that if there is no previous page/no next page those button options don't have an href (previously was showing pages in the href that didn't exist like blog/page/0 but the link wasn't clickable based on CSS we've added). 
- Added conditionals to show the blog listing home page vs. blog/page/1. 
Fixes #236 
Example blog: http://jrosa-102019231.hs-sitesqa.com/blog
**Checklist**
@TheWebTech @ajlaporte
=> Updating blog pagination to fix URL issue

src/css/objects/_layout.css
This pull request reduces the min-height that is set on elements with the class of "span" within an element with a class of "row-fluid". This looks like it was pulled over from Bootstrap 2 but isn't needed for a module drop zone in the editor. This should resolve an issue that was reported where a developer had multiple DND areas on a template but in the editor a user removed all modules in one of the DND areas, thus was getting a weird 28px gap that they couldn't remove. 
Example of page: 
Example in editor: 
Resolves #239 
**Checklist**
CC: @ajlaporte @TheWebTech
=> Reducing min-height in grid

src/modules/customizable-button.module/fields.json, src/modules/customizable-button.module/module.html, src/modules/pricing-card.module/module.html, src/modules/social-follow.module/module.html
- Checked through boilerplate for tabnabbing vulnerability. All modules within boilerplate were already working for this. I just swapped out the macro we were using for the new default snippet for link fields that includes the fix for adding `rel='noopener'` if a link is opened in a new window. 
- Added a label for the button link field for the button module.
- Removed HubSpot as the default link for the button module.
Resolves #233 
**Checklist**
=> Update links to prevent tabnabbing vulnerability

src/css/templates/_blog.css, src/templates/blog-index.html, src/templates/blog-post.html
In an effort to improve the out of the box accessibility and performance of the boilerplate blog, this PR does the following: 
- Swaps background images for images
- This allowed us to take advantage of the [native `loading` attribute](https://web.dev/browser-level-image-lazy-loading/)
- This allowed us to use a `width` attribute which should [enable automatic image resizing](https://developers.hubspot.com/docs/cms/developer-reference/cdn#image-compression-optimization-and-automatic-image-resizing)
- This allowed us to include an optional alt text for listing images
- This allowed us to include alt text for the author image on the author listing page
- Adds aria-label for links around listing images so there is discernible link text 
**Additional …
=> Swap background images for images and improve accessibility/performance for blog images

src/templates/partials/header.html
We use a conditional in the `header.html` file that shows/hides the language toggle depending on if the current page has a translation. This works for pages and posts but didn't account for blog listing pages. This update adds to the original conditional to also account for blog listing pages. 
Resolves #253 
**Checklist**
=> Update language conditional to account for blog listing page

src/templates/blog-index.html, src/templates/blog-post.html
- Changed h4 that was under the h1 in the blog header on the listing template to a paragraph tag (did this for the author listing page as well). 
- Rearranged code for blog header on listing pages a bit. Everything stays the same - I just realized we were repeating a few lines within a conditional and it would be DRYer to pull that out of the conditional. 
- Removed the blog header on the post template. That header had an h2 and an h4 and the post title (the h1) was set below the header. Removing this ensures that the blog headers stay in sequential order. 
[Example blog listing/post](http://jrosa-102019231.hs-sitesqa.com/blog)
Resolves #225 
**Checklist**
CC: @TheWebTech this doesn't impact the changes you were …
=> Fix blog markup

src/templates/qa-test.html
This had come up on a couple of calls with developers where it would be nice to have an out of the box test template that makes it easy to test things like typography, forms, etc. to ensure that everything is accounted for when doing QA. I've started off with a typography section, a forms section, and a theme module section for now but this can be easily added to or modified down the road based on feedback. By default it is set to `false` for `isAvailableForNewContent` so that this isn't accidentally used for an actual page. The idea would be that a developer would use this while developing a new theme but would delete it prior to finalizing the production/live environment (e.g. marketplace or live site). 
[Example …
=> Add a QA test template to boilerplate

src/templates/home.html
Fulfills the request to add a couple of examples of mobile editing in the boilerplate [via conversation here](https://github.com/HubSpot/cms-theme-boilerplate/pull/246). There weren't a ton of locations that would work for this but a couple areas in the home page were already using padding that could be reduced on mobile. This should provide a couple of examples for now and we can work to add more in in the future. 
Resolves #247 
**Checklist**
=> Adding a couple of mobile padding examples

src/modules/menu-section.module/module.html
Removing `aria-hidden` from the child menus. `aria-hidden` is set to false but doesn't get changed to true when someone hovers/focuses on a parent item. We are choosing to remove this for the time being to alleviate that issue. We chose not to set the attribute based on hover/focus for now as the behavior on desktop would not match mobile. We intend to update the menu more extensively to be fully accessible in the future. 
**FYI:** The mobile menu needs some accessibility work as well to be keyboard accessible but I think we can separate that work out for a separate issue for now. 
**Checklist**
Resolves #224
=> Remove aria-hidden

src/css/components/_header.css, src/templates/about.html, src/templates/blog-index.html, src/templates/blog-post.html, src/templates/contact.html, src/templates/home.html, src/templates/hubdb.html, src/templates/landing-page.html, src/templates/partials/header.html, src/templates/pricing.html, src/templates/qa-test.html, src/templates/system/404.html, src/templates/system/500.html, src/templates/system/backup-unsubscribe.html, src/templates/system/membership-login.html, src/templates/system/membership-register.html, src/templates/system/membership-reset-password-request.html, src/templates/system/membership-reset-password.html, src/templates/system/password-prompt.html, src/templates/system/search-results.html, src/templates/system/subscription-preferences.html, src/templates/system/subscriptions-confirmation.html
Adding a Skip Navigation/Skip to Main Content feature in the `header.html` file. Generally followed instructions [here](https://www.bignerdranch.com/blog/web-accessibility-skip-navigation-links). I put the navigation skipper within the `header.html` file to follow the [WebAIM website](https://webaim.org/techniques/skipnav/). I did not put it in the `header-no-navigation.html` file as there is no navigation in there but let me know if you think it still makes sense there/if there are any adjustments you think I should make. 
Example link: http://jrosa-102019231.hs-sitesqa.com/skip-nav
Resolves #213 
**Checklist**
=> Add nav skipper

src/templates/blog-post.html
Currently in the related posts macro there is no way to only show posts _if_ there is a related post available. This update uses `count` and `total` parameters to only show the posts and the section wrapper if there are posts available. 
Example link with related posts: http://jrosa-102019231.hs-sitesqa.com/blog/test-blog-post-0-0-0
Example link without related posts: http://jrosa-102019231.hs-sitesqa.com/blog/toy-story-4
Fixes #270 
**Checklist**
@TheWebTech @ajlaporte @JacobLett
=> Adjust macro to only show content if there is a related post

src/modules/card-section.module/fields.json, src/modules/card-section.module/module.html, src/templates/contact.html
Adding in the new [lazy loading](https://developers.hubspot.com/docs/cms/guides/speed/lazy-loading) option to images fields in custom modules (the only custom module that used this was card section). I defaulted the module to be set to `lazy` but the instance on the contact page to be set to `disabled` as all of the images show above the fold on desktop. 
Fixes #264 
**Checklist**
@TheWebTech @ajlaporte
=> Adding lazy load option to card section module

src/css/components/_header.css, src/templates/partials/header.html
We were getting flagged for the search field in the header not having sufficient contrast for color to background color. After discussing this, we decided to add a field label for the search field, remove placeholder altogether (as it would be redundant to the label), and remove the `color:transparent` previously set on the placeholder (so it would be visible for users using boilerplate that did want to add placeholder text). The placeholder attribute doesn't look like it can be removed right now (this has been flagged as an issue for the module itself).
Related to https://github.com/HubSpot/cms-theme-boilerplate/issues/282 
**Checklist**
@TheWebTech @ajlaporte
=> Fix search field

src/css/theme-overrides.css, src/fields.json
Setting the `fallback` property on fonts in `fields.json` so that a more appropriate fallback was set (e.g. sans-serif for a sans-serif Google font). 
Fixes #281 
**Checklist**
@jmclaren @ajlaporte
=> Setting fallback property for fonts in fields.json

STYLEGUIDE.md, src/css/components/_footer.css, src/css/components/_header.css, src/css/elements/_buttons.css, src/css/elements/_forms.css, src/css/elements/_tables.css, src/css/elements/_typography.css, src/css/fallback.css, src/css/objects/_containers-dnd.css, src/css/templates/_blog.css
This change splits out fallback CSS for `theme-overrides.css` from the `main.css` file into a separate `fallback.css` file which is optionally available if a developer doesn't want to use theme settings. The original purpose of putting fallback CSS for `theme-overrides.css` within `main.css` was so that a developer could use boilerplate with theme settings or without theme settings. The reason for this PR is to remove this redundant CSS from `main.css` which slightly helps performance (removes some unused render blocking CSS) and makes the CSS in `main.css` a bit easier to understand while still maintaining an option for developers who don't want to use theme settings. 
Resolves #285 
**Checklist**
CC: @jmclaren …
=> Split out fallback

src/css/main.css, src/templates/blog-index.html, src/templates/blog-post.html, src/templates/layouts/base.html, src/templates/system/404.html, src/templates/system/500.html, src/templates/system/backup-unsubscribe.html, src/templates/system/membership-login.html, src/templates/system/membership-register.html, src/templates/system/membership-reset-password-request.html, src/templates/system/membership-reset-password.html, src/templates/system/password-prompt.html, src/templates/system/search-results.html, src/templates/system/subscription-preferences.html, src/templates/system/subscriptions-confirmation.html
Add a block in the `base.html` file of the project to provide a space to optionally include template specific style sheets that you wouldn't want used on other templates via `main.css`. For example you wouldn't want to include the `blog.css` on the home template as that would be unused CSS that is render blocking. More detail can be found on this approach [here](https://pustelto.com/blog/optimizing-css-for-faster-page-loads/#page-based-code-splitting).
Fixes #289 
**Checklist**
=> Split out blog and system style sheets

src/css/components/_footer.css, src/css/components/_header.css, src/css/elements/_buttons.css, src/css/elements/_forms.css, src/css/elements/_tables.css, src/css/elements/_typography.css, src/css/fallback.css, src/css/templates/_blog.css, src/css/templates/_system.css, src/css/theme-overrides.css
- Removes unused or redundant CSS from the boilerplate style-sheets (duplicate CSS, CSS that isn't used, removing old selectors, consolidating selectors, etc.) 
- Rearranges some CSS in the header.css file so it is organized in a more logical way (e.g. grouping media queries under specified style vs. at the bottom of the style-sheet per https://github.com/HubSpot/cms-theme-boilerplate/blob/main/STYLEGUIDE.md#css-code-formatting # 14)
There are very little visual style differences with this update. The visual changes include: 
- Changing some of the blog elements spacing to be tied to the theme's vertical spacing setting in theme-overrides
- The search field border getting increased from 1.79px to 2px 
- Some very minor spacing changes so that the …
=> Remove unused or redundant CSS

src/templates/pricing.html
Updated the default button text on the pricing template to add context for screen readers. The default button pricing module button text is "Sign up for free" so that should have enough context by default. I'll also be updating the boilerplate demo website to reflect these changes. 
Fixes #300
**Checklist**
=> Updating default pricing button text to add context for screen readers

src/templates/partials/header.html
Currently the conditional around the language switcher in the `header.html` file accounts for translations on pages, blog posts, and blog listing. However, it doesn't account for if a blog listing has translated content but a blog post on the blog doesn't. This update to the conditional should account for that. 
Example blog listing with translated content:http://jrosa-102019231.hs-sitesqa.com/blog
Example blog post with translated content on that blog: http://jrosa-102019231.hs-sitesqa.com/blog/toy-story-4
Example blog post without translated content on that blog: http://jrosa-102019231.hs-sitesqa.com/blog/test-blog-post-0-0-0-0-0
**Checklist**
=> Update language switcher conditional to account for blog posts without translations

src/templates/layouts/base.html
Previously we were loading our style sheets via require_css which puts those style sheets at the top of the code included via standard_header_includes. We switched to using standard `link` elements for style sheets here (https://github.com/HubSpot/cms-theme-boilerplate/pull/297) so that we could use a code splitting technique for templates. In looking at performance scores pre and post the change, I noticed a dip because main.css and theme-overrides.css was getting loaded slower despite improvements to those files. It turns out that the load order (putting the `link`s below the standard_header_includes was what was causing the problem). This PR puts the `link`s above standard_header_includes so the loading order is similar to using require_css. …
=> Change CSS load order

src/css/templates/_system.css, src/js/main.js
Adding in vanilla JS to the `main.js` file for the theme's system `subscription-preferences.html` template. This JS looks to see if the global unsubscribe input is on the document and then will add/remove some classes and attributes to the surrounding checkboxes on that preferences form in order to disable the input. There are some additional styles in place to make the rest of the text label for that checkbox look disabled as well.
GitHub issue: https://github.com/HubSpot/cms-theme-boilerplate/issues/147
**Checklist**
=> Adding JS and styles for subscription preferences template disabled input

src/css/templates/_system.css, src/templates/system/search-results.html
Updating the system page templates so they are a bit cleaner looking. This PRs includes updates to the following:
- Remember me checkbox - Inlines the label next to the checkbox
- Show password text - make this a little smaller in font size
- Password pages error messaging - removes padding and margins around the `ul` and `li` so that messaging isn't bumped out in the form design
- Search results - now spans the full width of the container
- `.header` class restyled - this generic class was getting CSS from the header of the website, restyled this for system pages to remove the background color and other associated CSS bleeding over
- Submit inputs - Added some spacing/margin around these
**Checklist**
=> Updates to system page styles

src/modules/menu-section.module/module.css
Some of the default themes have had issues where the transitions in CSS are causing issues on the mobile breakpoint. This is only happening in the menu module and appears to be happening when theme settings are adjusted for the menu's background color. The transition on mobile isn't properly taking effect, so we've decided to remove the transition CSS on the mobile breakpoint only for background color.
**Checklist**
=> Removing transitions from the mobile breakpoint in the menu

src/css/elements/_typography.css, src/modules/card-section.module/fields.json
We had an issue with alt text being hard to read. After investigating it looks like this happened when an image had a small width set and was within a parent with `display: flex`. We have `word-break: break all` set by default so the alt text was stacking one letter on top of another. We adjusted some styles for the image tag which should target the alt text and removed the broken image in the module (as it wasn't required for the module and we were setting it at the template level). 
Resolves #324 
**Checklist**
=> Fix alt text

src/modules/menu-section.module/fields.json
Previously, the menu field wouldn't accept a `"default"` value of `"default"` to allow for a customer's default menu in their portal to be the placeholder. This caused issues for setting default content because you could only let the menu field be unselected, or, we have noticed providers leaving in IDs for menus that don't exist on a customer's portal. Setting the param `"default": "default"` will now point to a customer's default menu (as long as they have one in their portal)
**Checklist**
=> Adding "default" as the default menu for the menu-section.module 

src/templates/about.html, src/templates/home.html, src/templates/landing-page.html
Getting default image modules set up with lazy loading in preparation for the lazy loading option being added to the default image module. Also changing over all `image` to `linked_image` to remain consistent. The images that were set to lazy were any images below the fold on the home page template and any images below the fold on the landing page template. Examples of both in my test portal can be seen below: 
[Landing page](http://jrosa-102019231.hs-sitesqa.com/-temporary-slug-b559582a-b74e-48e2-88cd-c73097fc1014?hs_preview=GGDvfuxc-4490949455)
[Home page](https://preview.hs-sitesqa.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=L909nLdOFi1fSwJBZC1MwA&portalId=102019231&tc_deviceCategory=undefined&template_file_path=boilerplate-theme/ …
=> Setting lazy for loading on applicable default image modules

src/css/elements/_typography.css
Adds `overflow: auto` on the `pre` element to prevent responsiveness issues on mobile. In particular this was an issue on the boilerplate typography page and on the boilerplate `qa-test.html` template. 
Resolves #332 
**Checklist**
=> Adding overflow on pre element to fix responsiveness issue

src/modules/card-section.module/fields.json, src/modules/card-section.module/module.html
Turning on responsive options for the images in the card section. There were no particular reasons this was turned off to begin with so it seems to make sense to turn them on. This also adds in the HTML/HubL to support those responsive options. 
Resolves #336 
**Checklist**
=> Adjust card section module to account for responsive sizing options

src/css/components/_header.css
Puts the search field label inline with the search field as opposed to stacking them. I did keep them stacked on mobile because keeping them side by side didn't leave for much room in the field itself. 
[Example page](https://jrosa-102019231.hs-sitesqa.com/-temporary-slug-a078d5b3-b56d-43ce-b88b-ba81f1259fb3?hs_preview=XaqFcwCk-4516126583)
Resolves #302 
**Checklist**
=> Inlining label with search field in header

src/templates/about.html, src/templates/contact.html, src/templates/home.html, src/templates/landing-page.html
Adding custom max sizes to image modules within the template of the theme. This change will add the images max width/max height as the height/width attribute in the HTML which will help with reducing cumulative layout shift and help trigger automatic image resizing within HubSpot while keeping the image responsive. 
Fixes #336 
**Checklist**
=> Adding custom max sizes for images

src/css/components/_default-modules.css
Adds a max-width of 100% on certain modules that include images (e.g. logo, CTA, and rich text). The default image module has built in options for responsiveness already and I wanted to make sure this wouldn't mess with custom modules so I chose to not use the `:not` pseudo selector. 
Fixes https://github.com/HubSpot/cms-theme-boilerplate/issues/149 
**Checklist**
=> Adding max-widths on images  applicable images

README.md
Making a minor update to readme to remove left over reference to `master` branch that was changed to `main` branch a few months ago. CC: @ckconant
=> Updating master reference to reference new default main branch

src/modules/menu-section.module/module.css
Fixes issue with menu items not wrapping in child menus. There was a `white-space: nowrap;` that was set on `.submenu.level-1` which the child menus are contained in. After testing around I think it makes sense to remove this entirely vs. add `white-space: normal` to non level 1 submenus because forcing that on the top level menu items could break the site's responsiveness. 
Fixes #352 
**Checklist**
=> Fixing wrap on menu items

src/modules/menu-section.module/module.css
The submenu's z-index was a 1 on desktop therefore if a different item below it also had a z-index of 1 the submenu would flow behind it. To resolve this, I added `submenu { z-index: 2; }` per the suggestion of @DreamDevourer
Resolves #354 
**Checklist**
=> Fixing submenu z-index

src/js/main.js, src/modules/card-section.module/fields.json, src/modules/card-section.module/meta.json, src/modules/card-section.module/module.css, src/modules/card-section.module/module.html, src/modules/customizable-button.module/fields.json, src/modules/customizable-button.module/meta.json, src/modules/customizable-button.module/module.html, src/modules/pricing-card.module/fields.json, src/modules/pricing-card.module/module.css, src/modules/pricing-card.module/module.html, src/modules/social-follow.module/fields.json, src/modules/social-follow.module/module.html, src/theme.json
This pull request implements the new style fields feature on the boilerplate's modules. The style fields feature allows developers to add style related fields in the "style" tab of a module. 
[Best practices](https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields/best-practices)
[Changelog](https://developers.hubspot.com/changelog/style-fields-opt-in-beta)
[Sign up to participate in the style fields beta](https://docs.google.com/forms/d/e/1FAIpQLSeOnoO9ItSWEdplUwTtrJexWaihXoZkDqLI2qcvdZ3ESFJz6A/viewform)
**Notes**
We're currently omitting adding style fields to the menu as we are aiming to do a larger rebuild in the near future that will include some accessibility improvements. 
**Checklist**
CC: @TheWebTech
=> Add style fields to theme modules

src/css/components/_header.css, src/css/elements/_typography.css, src/css/objects/_containers-dnd.css, src/css/objects/_layout.css, src/css/templates/blog.css, src/css/templates/system.css, src/css/theme-overrides.css, src/modules/card.module/module.css, src/modules/menu.module/module.css, src/modules/pricing-card.module/module.css, src/modules/social-follow.module/module.css
Cleaning up some parts of the CSS including: 
- Removing *css-property workaround in layout.css that was designed to support IE 7 and older. 
- Making all comments sentence case
- Swapping px for rem where it made sense (generally kept pixels in cases like top, left, bottom, right / height and width in some cases / border and border radius. I swapped px for rem in cases of font size and spacing. Open to going another way if people have strong opinions on this. I mainly wanted to try to get to a somewhat more consistent place with this. 
Fixes #309 
**Checklist**
CC: @TheWebTech
=> Clean up CSS

src/css/theme-overrides.css, src/templates/blog-post.html
I think some styles specifically for the blog listing page got messed up upon the introduction of this update (https://github.com/HubSpot/cms-theme-boilerplate/pull/376). I think I missed some changed variable names which caused comment styles and blog listing post headings to be the wrong color (also blog listing post headings were not behaving properly on hover/focus). 
Example page: https://jrosa-102019231.hs-sitesqa.com/blog 
**Checklist**
=> Fix blog post title

src/templates/layouts/base.html, src/templates/system/404.html, src/templates/system/500.html, src/templates/system/backup-unsubscribe.html, src/templates/system/membership-login.html, src/templates/system/membership-register.html, src/templates/system/membership-reset-password-request.html, src/templates/system/membership-reset-password.html, src/templates/system/password-prompt.html, src/templates/system/search-results.html, src/templates/system/subscription-preferences.html, src/templates/system/subscriptions-confirmation.html
It was reported that our system templates do not support page titles. This PR adds custom page titles to system templates by setting a variable in each template, and conditionally using the variable if `page_meta.html_title` isn't present.
@TheWebTech @ajlaporte I took an initial pass at the titles for each template, but am highly open to any feedback/ recommendations.
**Checklist**
=> Add system template titles

src/templates/about.html, src/templates/blog-index.html, src/templates/blog-post.html, src/templates/contact.html, src/templates/home.html, src/templates/hubdb.html, src/templates/landing-page.html, src/templates/layouts/base.html, src/templates/pricing.html, src/templates/qa-test.html, src/templates/system/404.html, src/templates/system/500.html, src/templates/system/backup-unsubscribe.html, src/templates/system/membership-login.html, src/templates/system/membership-register.html, src/templates/system/membership-reset-password-request.html, src/templates/system/membership-reset-password.html, src/templates/system/password-prompt.html, src/templates/system/search-results.html, src/templates/system/subscription-preferences.html, src/templates/system/subscriptions-confirmation.html
Per suggestion of @jevenson we found that the `main` element and HubL comment above it was repeated for every template in boilerplate therefore to simplify the code it was moved to the `base.html` file. Per suggestion of @johnsfuller if someone wanted to add an aside that is adjacent to the `main` element they could add a new block for `aside` in `base.html` (example in linked GitHub issue below). 
Fixes #361 
**Checklist**
=> Move main element to base.html

src/modules/menu.module/module.html
Updates menu to account for menu items without a link. If the menu item without a link is a parent menu item/has children, we set the link to be: `<a class="menu__link menu__link--toggle" href="#" aria-haspopup="true" aria-expanded="false">{{ link.label }}</a>` otherwise if the menu item doesn't have a link _and_ doesn't have children we set the menu item to be `<span class="menu__link">{{ link.label }}</span>`. In this case we use a span to keep the menu items styled the same. 
[Example link](http://jrosa-102019231.hs-sitesqa.com/-temporary-slug-9cd7cf34-a3ff-48d4-8e45-57a987ddd6fe?hs_preview=iVKGGBFb-43115586653&#)
Fixes #377 
**Checklist**
=> Adjusting code for menu items without links

package.json
Updating boilerplate version to v3.1 to support the upcoming release. The plan is to set up the release for tomorrow afternoon. I want to let this last PR sit until tomorrow morning (https://github.com/HubSpot/cms-theme-boilerplate/pull/385) but if everything is good there I think we should be good for release.
=> Updating boilerplate version to 3.1

.github/workflows/deploy.yml, package.json
Update CLI and deploy version to be update to date. The CLI in particular was pretty out of date. Deploy action would be going from 1.3 to 1.4 (https://github.com/marketplace/actions/hubspot-cms-deploy).
=> Update cli and deploy version

.github/workflows/deploy.yml
Updates to use the latest published version of the GH action. That prior version may have had a bug preventing publishing.
Was reported by John Fuller of our dev community here:
https://hubspotdev.slack.com/archives/GUM1A8A9W/p1638991373123500?thread_ts=1638983484.122100&cid=GUM1A8A9W
**Checklist**
@jasonnrosa @anthmatic 
Not really sure how I would really test this change other than forking the whole repo so thought I'd PR since I don't know if we have any specific concerns with how we handle the boilerplate example site etc.
=> update deploy action version number in GH workflow

src/modules/card.module/fields.json, src/modules/card.module/module.html, src/modules/pricing-card.module/fields.json, src/modules/pricing-card.module/module.html, src/sections/cards.html, src/sections/pricing.html
This changes moves some text field over to rich text fields to allow for more flexibility on the content creators end and uses the rich text field config options to demonstrate how you can set some boundaries in terms of what someone can edit within those rich text fields. This also follows the same pattern in Growth in that for rich text fields, we don't have style fields that target them and instead we just offer the basic styling options via the rich text editor (e.g. alignment, font size, font family, etc.). We found that this pattern made more sense to users during user testing. 
Fixes #398 
**Checklist**
=> Updating module rich text fields to use the rich text field config options

src/css/theme-overrides.css
CSS for form textarea no longer uses nonexistent variable.
GitHub issue: #405
**Checklist**
@jasonnrosa
=> theme-overrides.css changed to use the correct variable for form textarea

src/css/theme-overrides.css
The font size portion of the button font styles was missing in theme-overrides. This adds that style in so that the button font size works properly. 
Fixes #412 
**Checklist**
=> Adding button font size in theme overrides

src/modules/blog-listings.module/module.html, src/modules/blog-pagination.module/module.html, src/modules/button.module/module.html, src/modules/card.module/module.html, src/modules/pricing-card.module/module.html, src/modules/social-follow.module/module.html
Stephanie put together a really thorough issue which is linked below. Essentially if you had a corner radius style field for a module, it wasn't possible to set the value to be explicitly 0px. Setting it to 0px would make the module fall back to whatever the default styles were. This was because our if statement to include the border-radius style was registering as false if the value for the number field was 0. I adjusted it per Stephanie's suggestion with using `{% if field >= 0 %}` rather than `{% if field %}`. 
Fixes #417 
**Checklist**
CC: @TheWebTech, @ajlaporte, and @StephanieOG
=> Fixing issue with corner radius of 0px

src/css/elements/_typography.css
Removes use of deprecated `word-break: break-word` and switches to `overflow-wrap: break-word`.
**Checklist**
CC: @jasonnrosa
=> Changed deprecated word-break: break-word to overflow-wrap

src/css/theme-overrides.css
There were a few warnings in the `theme-overrides.css` file that we found via the design manager. There were three incorrect references to field paths and one field reference that was outdated/no longer needed. 
**Checklist**
=> Resolving design manager warnings from theme-overrides.css

src/css/elements/_forms.css
The textarea field could previously be resized horizontally which didn't create a good user experience and could lead to responsiveness issues. I've set `resize: vertical;` on the textarea field to combat this.
Example video after fix: https://www.loom.com/share/dad765647762421a82f55830dbc36f0e
Fixes #426 
**Checklist**
=> Preventing textarea field from being resized horizontally

hubspot.deploy/cms-theme-boilerplate.yaml
⚠️ Please note this is an internal change that doesn't impact the actual boilerplate theme
**Description:** 
Removing teams from notifications in `cms-deploy.yaml`
=> Removing old teams from notifications

src/css/objects/_layout.css
This change tackles the following: 
- Updates `layout.css` file to use a flex grid vs. float for the grid
- Uses mobile first approach for media queries
- Uses CSS var for easily adjustable gap so it is easy to adjust
- Removes some extra helper classes that weren't being utilized in boilerplate
This approach takes a bit from the current Bootstrap 5 grid, takes inspiration from some work @stefenphelps had done [here](https://stefenphelps.com/blog/custom-grid-gutters-on-hubspot/) / work @anthmatic had done previously, and uses some of the existing concepts in `layout.css`. 
Notes/questions: 
- When `flex-wrap: wrap;` was set for `row-fluid` I noticed that `gap` wasn't factored into column width (similar to how `padding` would be with `box-sizing: …
=> Updating layout.css to use flex vs. float

src/css/generic/_normalize.css, src/js/main.js
We are stripping out IE specific code in favor of performance after [HubSpot had dropped support for IE](https://developers.hubspot.com/changelog/end-of-ie-support) and now more recently [Microsoft dropped support for IE](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support). This change just removes some old IE specific CSS/JS(polyfill) code. I also removed IE11 from the supported browsers list in the repo Wiki.
For the suggestions on removing `zoom` from the original issue - it looks like this was tackled in an earlier PR here (https://github.com/HubSpot/cms-theme-boilerplate/commit/0f7a2fd17b5d2db79640fc90aa27ac38ee80005a). 
GitHub issue: Fixes #367 
**Checklist**
CC: …
=> Stripping code specific for IE

.vscode/extensions.json
Upon opening the repo locally for the first time VS Code users will be recommended to install the HubSpot VS Code Extension. Making it easier for users to become aware of it. Additionally a user can trigger viewing the recommended extensions intentionally by using the `Extensions: Show Recommended Extensions`. The recommendation should not appear for anyone who already has the extension installed.
**Checklist**
@jasonnrosa
=> Add recommendation for using hubspot vs code extension

src/theme.json
Updating author email used in `theme.json` as we are moving away from the previous email that was listed there
=> Updating email referenced in author information

.blazar.yaml
We now reference buildpacks by name rather than a github location
Example page:
GitHub issue:
**Checklist**
=> Specify buildpack name not location

cms-deploy.yaml
Fixing module IDs in `cms-deploy.yaml`. This was causing some issues in the build which is used when the theme gets delivered to portals as a getting started option in design manager but it didn't get flagged until recently after [this was merged in](https://github.com/HubSpot/cms-theme-boilerplate/pull/444). 
CC: @joeyblake @ionian-exile
=> Fixing module IDs in cms-deploy.yaml

src/css/objects/_layout.css
This utilizes variables and loops to make the `_layout.css` a bit more DRY. It also fulfills #450, by removing the catch-all "span" attribute selector.
GitHub issue: https://github.com/HubSpot/cms-theme-boilerplate/issues/450
**Checklist**
=> Update `layout.css` to be a bit more DRY and explicit

src/css/main.css
It's just a minor typo error I found. The body tag should be `<body>` instead of `<body<`
Example page:
GitHub issue:
**Checklist**
=> <body> tag with the correct closing character

src/fields.json
- Revert
`alternate_names` were added to the fields.json for the theme, but there [are some discussions](https://hubspot.slack.com/archives/C04CWRTJZSB/p1679499758790889) about changing how these should work. We may reincorporate these in the future but for now we'll remove them.
=> Remove alternate_names

src/css/elements/_buttons.css, src/css/theme-overrides.css
Per the issue linked below, theme styles applied to theme settings wouldn't apply to the default button module which can be confusing for a user. We have some plans to make this better long term in other ways (e.g. in this case I think improving the default button and not having a theme specific version would help/being able to hide the default in favor of a theme module; and being able to reliably inherit from theme settings from default modules will also help) but in the interim this should help ensure that theme settings apply to the default and theme module in this case. 
Example page: [Example page with default and theme module stacked on top of each other](https://jrosa-102019231.hs-sitesqa.com/testing-button)
GitHub issue: …
=> Adding hs-button class to theme button styles

src/templates/partials/header-no-navigation.html, src/templates/partials/header.html
Update instances of @hubspot/logo in templates to use appropriate lazy_loading. Header instances are set to "eager"
=> update: logo lazy loading attribute in templates

package.json, src/fields.json
Seems like h5 inheritance from `theme.global_fonts.secondary.color` might have been forgotten. This PR links it back up. 
More [details](https://hubspot.slack.com/archives/C0225PER3TM/p1686948320414699). 
Example page:
GitHub issue:
**Checklist**
=> update: connect h5 to inherit from secondary font color

package.json, src/css/components/_header.css, src/templates/partials/header.html
This update adds template support for the new `language_switcher` version.  Styles overall are pretty close but have been updated a bit. [DEMO PAGE](https://885068889.hs-sitesqa.com/fr/multi-lang?hsCacheBuster=9646)
|----OLD----| ----- NEW -----| -------- Description ------ |
|--|---|---|
|![2023-06-27 15 47 32](https://github.com/HubSpot/cms-theme-boilerplate/assets/39243773/ac910d66-a058-4dd5-8de4-2c40702e4ce6) | ![2023-06-27 15 46 08](https://github.com/HubSpot/cms-theme-boilerplate/assets/39243773/946e2204-63a8-4319-a893-1d953f0e973f) | Mobile View |
| ![2023-06-27 15 47 09](https://github.com/HubSpot/cms-theme-boilerplate/assets/39243773/314e514a-15e1-4918-9b30-0183d5e58cbf) |  ![2023-06-27 15 45 …
=> update: prep work for lang switcher versioning

package.json, src/modules/button.module/fields.json
Adds the CTA link type to the button module. This allows users to link to pop-up ctas if they have them enabled on their portal. 
**Checklist**
=> update: add cta link type to button module

src/fields.json
We reviewed all of the boilerplate templates as part of an accessibility audit, and found that `<a>` tags failed the ["Links must be distinguishable without relying on color"](https://dequeuniversity.com/rules/axe/4.8/link-in-text-block?application=AxeChrome) rule. Allowing `<a>` tags to have an underline satisfies this requirement, so we're removing the field default which removes them. 
**Checklist**
=> Allow <a> tags to have underline
