- .github/workflows/deploy.yml
- bin/deploy.sh
- bin/generate-config.js
- package.json
> Add workflow to auto-deploy to the boilerplate portal

- src/css/_forms.css
- src/css/main.css
This PR makes a few tweaks for forms:
- Sets a max width & config variable
- Lines up radio/checkboxes and labels
- Forces fields to fill 100% when multiple columns are used
> Design tweaks for forms

- src/css/_header.css
- src/modules/Menu section.module/module.css
- src/modules/Menu section.module/module.html
- src/modules/Menu section.module/module.js
This PR includes the following improvements from Axel:
- add active page styles for active menu items
- center align search bar and navigation for large logos
- search bar keeps focus style when text is inputted
- fixed hover states and keyboard focus for desktop and mobile
- make the unhover animation a bit smoother
- fix mobile icon toggle, makes open + collapsed states easier to view
- added unhighlight transition to the small triangle
> Improve header and navigation

- src/templates/partials/footer.html
- src/templates/partials/header.html
> Add labels for the header and footer to improve global content editing

- README.md
Adds a link to the beta developer terms in the README
> Add beta terms link

- src/modules/Card section.module/meta.json
- src/modules/Customizable button.module/meta.json
- src/modules/Menu section.module/meta.json
- src/modules/Pricing card.module/meta.json
- src/modules/Social follow.module/meta.json
> Add module icons

- src/css/_typography.css
- src/css/main.css
- src/templates/layouts/base.html
Reverts HubSpot/cms-theme-boilerplate#21
Demo success!
> Revert "A few design tweaks (not designer approved)"

- src/css/_blog.css
> Center blog comment

- src/css/_header.css
- src/modules/Menu section.module/module.css
- src/templates/partials/header.html
Kept the previous font size decrease but added a stacked search and nav bar
> added a tablet-sized breakpoint for the header

- src/templates/homepage.html
- src/templates/layouts/base.html
> Use get_asset_url where possible (include with raw assets)

- src/css/_blog.css
- src/templates/blog-index.html
For blog "Tag Pages", we need to display the tag name and prevent the first blog post from displaying large format:
> Implement blog tag page design

- src/css/_landing.css
- src/css/main.css
- src/templates/homepage.html
- src/templates/landing-page.html
- src/templates/layouts/base.html
- src/templates/partials/header_landing_page.html
created another page template for spinning up landing pages
> Added a landing page template

- README.md
- bin/deploy.sh
> updated the documentation + deploy script to use the new cms tools command

- src/css/_typography.css
> added some simple blockquote styles

- src/templates/about.html
- src/templates/blog-index.html
- src/templates/blog-post.html
- src/templates/contact.html
- src/templates/homepage.html
- src/templates/landing-page.html
- src/templates/partials/footer.html
- src/templates/partials/header.html
- src/templates/partials/header_landing_page.html
- src/templates/system/404.html
- src/templates/system/500.html
- src/templates/system/backup_unsubscribe.html
- src/templates/system/password_prompt.html
- src/templates/system/search_results.html
- src/templates/system/subscription_preferences.html
- src/templates/system/subscriptions_confirmation.html
I added labels to each of the templates in the boilerplate. Labels will be visible in the UI for the user when they select a new template to create a page.
> Adding labels to templates

- package.json
Hi all, 
Just a quick change that I make when I clone this repo, thought it might be nice to include the change in the main repo itself. :-) 
Thanks, 
George
> Update package.json to remove duplicate scripts key

- .blazar.yaml
- cms-deploy.yaml
Allow the boilerplate theme to be built with Blazar
> Add Blazar Build

- README.md
Removes beta verbiage from readme.
> Remove beta from readme

- src/README.md
- src/css/theme-overrides.css
- src/fields.json
- src/templates/layouts/base.html
- src/theme.json
This PR modifies the Boilerplate project to be a Theme. To learn more about Themes, and join the Themes for developers beta, read the information below!
A Theme is a portable and contained collection of developer assets designed to work together to enable a marketer-friendly content editing experience.  
Themes allow developers to create a set of Theme Fields, similar to Module Fields, which allow content creators to tweak various knobs and dials designed by a developer to allow global stylistic control over a website without having to edit CSS. Developers use HubL to access the values of Theme Fields throughout their CSS. Content creators use the Theme Editor to modify Theme Fields, preview those changes against existing templates within a Theme, and publish their changes.
The Theme …
> Make the Boilerplate a Theme (BETA)

- src/css/_footer.css
- Footer content now has a container that's consistent with the rest of the theme container settings
- footer content stayed centered
> added max width spacing to footer

- src/css/_system_pages.css
- src/templates/system/password_prompt.html
Updating password prompt template.
- Adds header content above the form
- Adds some CSS to the system page to style password prompt form
> Updating password prompt template content

- README.md
- STYLEGUIDE.md
> Added a style guide to boilerplate

- src/templates/contact.html
- src/templates/homepage.html
- src/templates/partials/footer.html
- src/templates/partials/header.html
- src/templates/pricing.html
Fixes module references after module folder renaming to kebab case.
> Fixing references to modules after file name change

- package.json
- yarn.lock
Keeping the boilerplate up to date
> Updated the HubSpot CMS tools dependency

- STYLEGUIDE.md
Making minor adjustments to the style guide of the boilerplate project: 
- Removing experimental sections
- Fixing formatting issues
- Adding line breaks to distinguish sections 
- Adding some additional examples in certain sections
> Modifications to style guide

- STYLEGUIDE.md
Updating headers in style guide to use sentence casing. CC: @ckconant
> Sentence casing headers in style guide

- cms-deploy.yaml
- package.json
Update boilerplate version to 1.1.0
> Update boilerplate version to 1.1.0

- src/templates/homepage.html
Adding a comment on the home template to speak to best practice on the h1 tag
> Adding comment to home template

- src/css/theme-overrides.css
- src/modules/social-follow.module/fields.json
- src/modules/social-follow.module/meta.json
- src/modules/social-follow.module/module.css
- src/modules/social-follow.module/module.html
Reverts HubSpot/cms-theme-boilerplate#91 - it looks like this pulled over some unintended styles
> Revert "Updating social follow module"

- cms-deploy.yaml
Added a new config value to cms-deploy files
> Set field inHollow: false

- src/css/theme-overrides.css
- src/fields.json
- src/modules/social-follow.module/fields.json
- src/modules/social-follow.module/meta.json
- src/modules/social-follow.module/module.css
- src/modules/social-follow.module/module.html
Added back changes from (https://github.com/HubSpot/cms-theme-boilerplate/pull/91). Some styles were getting picked up from Sprout so I reverted the PR and added/removed a few extra styles. I also added some :hover, :focus, and :active states to fix the issue here #97 
Loom of update: https://www.loom.com/share/fa41fc1e0483417abcf53f399a655099
> Re-adding social follow module with updated styles

- src/modules/card-section.module/fields.json
- src/modules/card-section.module/meta.json
- src/modules/card-section.module/module.css
- src/modules/card-section.module/module.html
- src/modules/customizable-button.module/fields.json
- src/modules/customizable-button.module/meta.json
- src/modules/customizable-button.module/module.html
- src/modules/menu-section.module/fields.json
- src/modules/menu-section.module/meta.json
- src/modules/menu-section.module/module.css
- src/modules/pricing-card.module/fields.json
- src/modules/pricing-card.module/meta.json
- src/modules/pricing-card.module/module.css
- src/modules/pricing-card.module/module.html
- src/modules/social-follow.module/meta.json
- src/modules/social-follow.module/module.css
Updated boilerplate modules to meet style guide requirements: 
- Used single quotes in HubL 
- Removed unnecessary JSON in fields.json
- Organized fields.json fields
- Organized meta.json fields
- Set labels on module fields and module labels to sentence casing
- Removed numbered IDs in module fields.json with dot notation (using field `name`)
- Alphabetized CSS
- Added vendor prefixes 
- Set all colors to capital hex (shortened where possible e.g. #FFF) 
- Remove unneeded JS files from modules that don't use JS
- Fixed incorrect usage of BEM classes 
- Removed the unit identifier for length values that are set to 0
> Style guide modules

- src/modules/social-follow.module/fields.json
Fixing `link` param on social follow module and setting default link values.
> Fixing link param and default links

- src/templates/layouts/base.html
Update base.html to meet the style guide: 
- Remove comment in block body
- Add block for footer (similar to header)
- Update HTML + HubL to meet the style guide requirements
> Style guide base.html

- src/templates/landing-page.html
- src/templates/partials/footer.html
- src/templates/partials/header-no-navigation.html
- src/templates/partials/header.html
Update partials to meet style guide requirements: 
- Update HTML + HubL in partials to meet style guide 
- Renaming header no navigation partial so that it wasn't specific to the landing page template (could be used elsewhere)
> Style guide partials

- src/theme.json
There does not exist a homepage.html template.
> Update theme.json to fix preview

- src/js/main.js
- src/modules/menu-section.module/module.js
- Updating JS to meet style guide (just needed to swap double quotes for single in some locations). 
- Adding polyfill for Nodelist forEach so that it works properly in IE. 
Fixes #89
Fixes #129
> Updating JS to use single quotes and adding forEach polyfill

- package.json
Updating version for boilerplate patch release (1.2.2)
CC: @TanyaScales @ckconant
> Updating version in preparation for patch release

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
- CONTRIBUTING.md
- README.md
- Add a bug report issue template
- Add a feature request issue template
- Add a pull request template
- Update the contributing.md file
- Update readme.md file
Fixes #143 
Fixes #142 
CC: @TheWebTech @ajlaporte
> Add community related files

- package.json
Bumping up version of boilerplate `package.json` to include recent bug fix for new patch release.
> Update version for 1.2.4

- src/templates/home.html
Quickly updating button text on home page to help resolve flag we're getting in SEO section of website grader for non-descriptive link text. 
**Checklist**
CC: @TanyaScales @ckconant
> Updating default button text

- src/css/components/_header.css
- src/css/theme-overrides.css
- src/modules/menu-section.module/module.css
- src/modules/menu-section.module/module.html
Previously the triangle at the top of the dropdown menus in the main navigation was using a `div` as a child of a `ul` which is invalid HTML. This has since been fixed up to use a pseudo element. The borders have also been adjusted to be an even 2px in width (was previously 1.79px which was causing some consistency issues in certain browsers). Drop down menus have also been moved slightly closer to the parent menu item so there was an issue when hover between parent and child menu. I also made some adjustments to ensure everything is properly hooked up to theme settings. 
Related to: https://github.com/HubSpot/cms-theme-boilerplate/issues/181
**Checklist**
> Adjust menu

- README.md
Updated readme to include new badges related to site performance. 
**Checklist**
CC: @ckconant @TanyaScales
> Add readme badges to reflect performance updates

- package.json
Updating boilerplate to version 1.3 to support new release.
> Update version to 1.3

- package.json
Updating boilerplate version in preparation to make a patch version update.
> Adding new patch version

- cms-deploy.yaml
Re-scoping the theme for customers with `website-theme-write-access` for Marketing Hub Pro/Enterprise
**Checklist**
@gcorne
> Scope CMS Theme Boilerplate to website-theme-write-access

- src/templates/hubdb.html
Updating copy in first comment of HubDB template
> Updating copy in first comment of HubDB template

- yarn.lock
Updating `yarn.lock` file based on dependency updates in `package.json` https://github.com/HubSpot/cms-theme-boilerplate/pull/230
**Checklist**
CC: @ckconant @TanyaScales
> Upgrading yarn lock based on on package.json updates

- package.json
Updating version to get ready for v1.4 release
> Updating version to prepare for new release

- src/templates/partials/footer.html
This adds a label to the text module in the footer so that the purpose of the text module was clearer. 
Fixes #227 
**Checklist**
> Adding label for footer text module

- src/theme.json
Adding the new responsive breakpoints for themes in boilerplate ([documentation on the feature can be found here](https://developers.hubspot.com/docs/cms/building-blocks/themes/responsive-breakpoints)). 
Resolves #244 
**Checklist**
CC: @jmclaren @ajlaporte
> Adding mobile breakpoints to theme.json

- src/templates/partials/header.html
I missed the mobile toggle when making the update to the conditional here (https://github.com/HubSpot/cms-theme-boilerplate/pull/254). This should fix that up and resolve the console error that is being caused as a result. 
**Checklist**
> Updating language toggle for mobile to account for blog listing

- src/license.txt
- src/theme.json
Adding a placeholder license file via the new `license` property in `theme.json`. I added some instruction in there to help a user get started and linked where this property will be documented . I could also just cut down on the instructions in there and only link to the doc. Let me know what your preference is @TheWebTech 
Resolves: #256 
**Checklist**
@williamspiro
> Adding license placeholder for boilerplate

- src/css/templates/_system.css
- src/templates/system/404.html
- src/templates/system/500.html
- src/templates/system/membership-login.html
- src/templates/system/membership-register.html
- src/templates/system/membership-reset-password-request.html
- src/templates/system/membership-reset-password.html
- src/templates/system/search-results.html
We're updating the system page templates that have hard-coded content to use RTEs
- Updates system pages with content to use RTE
- Updates error page headings: removed the class assigned to these.
- Updates error page button: Separated this out to a themed button module with appropriate markup.
- Updates paragraphs with introduction class: removed the class assigned to these.
**Checklist**
> Update to system page templates

- .blazar.yaml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- README.md
- hubspot.deploy/cms-theme-boilerplate.yaml
We are working on updating the `master` branch to be named `main`. Prior to making that change I wanted to have a pull request ready so that all files are updated accordingly after making that change. Please let me know if you have any questions or concerns about the change!
Related to: #261 
**Checklist**
@TheWebTech @ajlaporte @gcorne @KatzMitch
> Updating files to support master branch rename

- .blazar.yaml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- README.md
- hubspot.deploy/cms-theme-boilerplate.yaml
Merging over remaining changes from master to main
> Merging changes from master to main

- package.json
Updating the new version number of boilerplate in `package.json` to prepare for version release
CC: @TanyaScales @ckconant
> Updating the new version number in package.json

- .npmrc
- package-lock.json
- package.json
- src/css/components/_default-modules.css
- src/css/components/_header.css
- src/css/elements/_forms.css
- src/css/templates/_blog.css
- src/css/templates/_system.css
- src/modules/card-section.module/module.css
- src/modules/menu-section.module/module.css
- src/modules/pricing-card.module/module.css
- src/modules/social-follow.module/module.css
Added auto prefixer package to `package.json` and included a script that allows someone to run auto prefixer locally. I also ran autoprefixer on our existing files afterwards (and removed any HubL from the files that autoprefixer was run on). We specifically ignore a few files in the npm config file (`npmrc`) for files that are primarily HubL. 
Fixes #266 
**Checklist**
@jmclaren @ajlaporte
> Add auto prefixer and run auto prefixer

- package-lock.json
- package.json
Updating CMS CLI version in `package.json` to be up to date
**Checklist**
@ckconant @TanyaScales @anthmatic
> Updating the HubSpot CMS CLI version in package.json

- .github/workflows/deploy.yml
Bumps version of GH deploy action to prevent incompatible CLI dep
https://github.com/HubSpot/hubspot-cms-deploy-action/pull/4
**Checklist**
@jasonnrosa
> Use newer version of GH action

- src/css/elements/_typography.css
- src/js/main.js
There are a few things off about the `main.js` file. There are a couple of bugs in specific templates (e.g. landing page where we had an event listener on the menu but menu wasn't on this template), the code is a bit tough to read through, and there is old JS that is no longer needed that can be removed/cleaned up. Therefore we are refactoring the JS file to be a bit more simple and easier to read. 
Solving some of the bugs is also resulting in a performance boost as it looks like a broken event listener was slowing down the page load of the blog post template/landing page template. 
Fixes #276 
Fixes #290 
Related to #167 
**Checklist**
CC: @TheWebTech @ajlaporte
> Refactor main.js

- src/modules/card-section.module/fields.json
- src/modules/card-section.module/module.css
- src/modules/card-section.module/module.html
- src/templates/contact.html
Made a few changes to improve the card section module which include: 
- Fixing an issue with how lazy loading was set up (it wasn't in the context of the loop so therefore was having some issues
- Added height and width attributes for the image and removed the forced image width of 100%
- Added a choice field for the title that only shows if the title has some text filled out
- Adjusted some of the margins to flow normally with the vertical rhythm established in the theme. 
Example page: http://jrosa-102019231.hs-sitesqa.com/-temporary-slug-80e59544-07f8-43f3-a052-10ad708940c9?hs_preview=HBMhMcmW-4412458880
**Checklist**
> Clean up the card section module

- src/css/fallback.css
- src/css/theme-overrides.css
- src/modules/pricing-card.module/fields.json
- src/modules/pricing-card.module/module.css
- src/modules/pricing-card.module/module.html
- src/templates/pricing.html
A few minor changes to improve the pricing card module including: 
- Changing price from heading to paragraph tag as the price didn't fit the purpose of a heading (thank you for the help here @TanyaScales ).
- Added a heading type selector for the main heading in the pricing card
- Changed the wrapping of each card from a div to a section
- Removed unused/redundant styles
- Added the card__price selector into theme overrides to style it like an h3 still
- Removed some unused module styles in theme overrides while adding the above style in
Example page: https://preview.hs-sitesqa.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=1OQhFELOX_-wNVF3DHxmqw&portalId=102019231&tc_deviceCategory=undefined&template_file_path=boile …
> Update pricing card module

- src/css/templates/_blog.css
- src/templates/blog-index.html
- src/templates/blog-post.html
Adding some updates to make the boilerplate more accessibility friendly. Little more SEO friendly.
For those wanting to understand the pagination changes:
https://www.a11ymatters.com/pattern/pagination/
Add rel for author and tags to communicate relationship of the page to search engines. Likely has no a11y value.
This is a draft I intend to add more updates.
Example page:
GitHub issue:
**Checklist**
> Updated pagination to be better for assistive technology users

- src/css/templates/_blog.css
Adding style to timestamp to go along with this fix (https://github.com/HubSpot/cms-theme-boilerplate/pull/238)
**Checklist**
> Add style to timestamp

- src/templates/blog-post.html
- src/templates/layouts/base.html
- src/templates/partials/footer.html
- src/templates/partials/header-no-navigation.html
- src/templates/partials/header.html
- src/templates/qa-test.html
Updating some of the comments throughout the boilerplate. Overall after looking around most of the files that are available to be marked up with comments (e.g. non `json` files) already have a decent amount of comments. I think we are in a decent spot and we should now just update the Wiki to make sure it is fully up to date. 
Fixes: #167 
**Checklist**
> Adding and updating comments in the templates

- package.json
Updating version of boilerplate for upcoming release (planning on publishing the release on the week of the 4th after the holidays). 
CC: @TanyaScales @ckconant @TheWebTech @ajlaporte
> Updating version for boilerplate for upcoming release

- .github/workflows/deploy.yml
Fixes an internal issue where the GH Action used to auto deploy was failing
Example page:
GitHub issue:
**Checklist**
@jasonnrosa
> Bumped GH Action version to fix deploy issue

- src/templates/blog-index.html
- src/templates/blog-post.html
Separating blog template types (blog_post and blog_listing)
Fixes #245 
**Checklist**
@TheWebTech @ajlaporte @williamspiro
> Separating template types for blog post and blog listing

- src/js/main.js
Updating the recently merged code for the `subscription-preferences.html` system template in order to handle multiple subscriptions on the form.
**Checklist**
> Updating to use for each loop for multiple subscriptions

- src/css/components/_footer.css
- src/css/components/_header.css
- src/css/fallback.css
- src/css/main.css
- src/css/theme-overrides.css
- src/templates/partials/footer.html
- src/templates/partials/header-no-navigation.html
- src/templates/partials/header.html
Adding drag and drop support in global partials (header, footer, and header no navigation). 
Fixes #291 
**Checklist**
> Convert global partials to use drag and drop 

- src/modules/customizable-button.module/module.html
I'm adding the conditionals that handle various URLs for the button's link field. These match our default themes. Additionally, by adding these scenarios, a bug needs to be fixed for the use of `/` as an external url into the `button.module`. This is used as a part of the 404 system pages and currently the button sets the `href` to `///` by mistake. This PR corrects that and allows the use of `/` as the `href` value.
**Checklist**
> Adding more conditionals to handle various href scenarios

- package.json
Bumping version to 2.0.0 in preparation for a release today. 
CC: @williamspiro @jmclaren @ajlaporte
> Bumping version in preparation for release

- package.json
Bumping version in package.json to v2.1.0 in preparation for release
CC: @ckconant @TanyaScales @jmclaren @ajlaporte
> Bump version to 2.1

- package.json
Update boilerplate version to 2.2. This is pending remaining PRs here (https://github.com/HubSpot/cms-theme-boilerplate/projects/10) get merged first.
> Update version to 2.2

- src/templates/partials/header.html
The current language switcher conditional in the header only shows the language switcher if there is a language variation of that page however it doesn't account for if that page is published or not. This update ensures that the language variation is published in order for the language switcher to show. 
**Checklist**
> Updating language switcher conditional to account for a page with an unpublished language variation

- package.json
Update boilerplate version to 2.3. This is pending remaining PRs here (https://github.com/HubSpot/cms-theme-boilerplate/projects/11) get merged first.
> Update version to 2.3

- .github/pull_request_template.md
Quick fix to our PR template (Jon's handle was not correct there).
> Updating Jon's GitHub handle in the PR template

- src/sections/call-to-action.html
- src/sections/cards.html
- src/sections/hero-banner.html
- src/sections/multi-column-content.html
- src/sections/multi-row-content.html
- src/sections/pricing.html
Adding descriptions to sections (these were previously omitted but it would be good to have an example of them in boilerplate). 
Fixes #370 
**Checklist**
> Adding section descriptions

- src/css/components/_header.css
- src/css/elements/_buttons.css
- src/css/elements/_forms.css
- src/css/elements/_tables.css
- src/css/elements/_typography.css
- src/css/templates/system.css
- src/css/theme-overrides.css
- src/fields.json
- src/modules/menu.module/module.css
Updating theme settings to follow new [recommended UX patterns](https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields/best-practices). I also added some additional theme settings and tried to clean things up a bit. This also swaps out old settings for new style fields (e.g. border, spacing, etc.). 
Fixes #308 
Fixes #92 
Fixes #360 
**Checklist**
CC: @TheWebTech
> Update theme settings

- src/css/components/_header.css
- src/css/theme-overrides.css
- src/modules/menu.module/module.html
Fixing border of drop down menus on mobile and adjusting border radius of lang switcher to match that of the regular menu drop down. 
**Checklist**
CC: @TheWebTech @ckconant
> Fixing border on mobile and adjusting border radius on lang switcher

- package.json
Updating version in preparation for release of v3.0
> Updating version in preparation for release

- src/modules/blog-listings.module/module.css
- src/modules/blog-listings.module/module.html
Adding a couple of subheadings within the blog listing module to serve the purpose of a tag/author listing. This can be built up to be a bit more robust but I'm intentionally keeping it on the simpler side for the time being. Let me know if you have any thoughts on anything we might want to add/the current implementation in terms of where things stand for the blog editing experience right now. 
Fixes #357 
**Checklist**
CC: @TheWebTech @ajlaporte @williamspiro
> Adding in headers for tag and author listing pages

- src/modules/blog-listings.module/fields.json
- src/modules/blog-listings.module/module.html
Currently we are hard coding in the tag listing and author listing title. We've added fields so that these are editable (particularly relevant for non-English sites/multi-lang sites). 
Fixes #388 
**Checklist**
> Adding fields for editing blog tag and blog author listing headings

- package.json
Updating version from v3.1 to v3.2 in preparation for upcoming minor release
> Updating version in package.json in preparation for release

- src/modules/blog-listings.module/module.html
- src/modules/blog-pagination.module/module.html
- src/modules/button.module/module.html
- src/modules/card.module/module.html
- src/modules/menu.module/module.html
- src/modules/pricing-card.module/module.html
- src/modules/social-follow.module/module.html
This makes the style tag appear in the <head> instead of the <body> making it valid HTML.
Example page:
GitHub issue:
**Checklist**
@jasonnrosa
> add require css block tag around style blocks

- package.json
Updating version from v3.2 to v3.3 in preparation for upcoming minor release
> Updated version in package.json in preparation for release

- src/theme.json
Add a few of the missing theme fields that the HubSpot Asset marketplace requires.
> Update theme.json with missing fields

- src/modules/social-follow.module/fields.json
Swapping the default icon for the "custom icon" field in the social follow module to a non-HubSpot icon. 
**Checklist**
> Swapping out default icon

- package.json
Updating boilerplate version to v3.4 to support the upcoming release. We should be rolling this out this afternoon.
> Updating version in package.json to v3.4 in preparation for release

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- CONTRIBUTING.md
Updating contributing guide and issue templates to include a note about contacting support for HubSpot product specific issues.
> Updating contributing guide and issue templates

- STYLEGUIDE.md
- src/theme.json
Updates the theme label in theme.json to be title case, and updates the STYLEGUIDE.md to match for consistency.
Example page:
GitHub issue:
Addresses Issue #411 
**Checklist**
- [x ] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [x ] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [ x] I have thoroughly tested my change.
> Title case theme.json label

- src/modules/pricing-card.module/fields.json
- src/modules/pricing-card.module/module.css
- src/modules/pricing-card.module/module.html
- Enhancement (change which improves upon an existing feature)
Add payment link design option to add payment links to pricing module.
**Checklist**
- [ Y] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [Y ] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [ Y] I have thoroughly tested my change.
CC: @TheWebTech @ajlaporte
> content asset issue #660: add payment link to pricing module

- package.json
Version bump to prepare for release
> bump version to prepare for release

- package.json
forgot to reset the patch verison in the last version bump. Taking care of that now
version bump
Resetting patch version. Forgot to do this on the last version bump. 
**Checklist**
- [ x ] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [ x ] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [ x ] I have thoroughly tested my change.
> version bump reset patch version

- src/fields.json
- [ x ] Enhancement (change which improves upon an existing feature)
update instances of brandSettings to brand_settings (snake case) [open issue](https://git.hubteam.com/HubSpot/content-assets/issues/717)
**Checklist**
- [ x ] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [ x ] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [ x ] I have thoroughly tested my change.
> update: swap brand settings case

- src/templates/layouts/base.html
Updating favicon to reference brand_settings instead of site_settings as that will be the new preferred location to pull from. 
**Checklist**
> Updating favicon to reference brand_settings

- src/fields.json
Add initial support for alternate_name field. This is only added into theme settings and only for primary_color, secondary_color, body_font, heading_font
> feature: add alternate_names

- src/modules/button.module/meta.json
- src/modules/card.module/meta.json
- src/modules/menu.module/meta.json
- src/modules/pricing-card.module/meta.json
- src/modules/social-follow.module/meta.json
Adds module categories to the boilerplate theme modules ([link to documentation on the new feature here](https://developers.hubspot.com/docs/cms/building-blocks/modules/add-categories))
**Checklist**
> Add module categories

- src/css/elements/_typography.css
Adds a couple of comments in the typography.css file to explain the usage of overflow-wrap and direct developers to using a better solution depending on their use case. Also notes the specific CSS for certain languages which can be safely removed if someone doesn't have their site in one of those languages. 
[Related to this conversation](https://github.com/HubSpot/cms-theme-boilerplate/pull/410)
**Checklist**
CC: @johnsfuller @JacobLett
> Adding a comment to explain purpose of overflow wrap in typography.css
